---

# http://www.aberdeencloud.com/docs/guides/command-line-tools

- name: Install AberdeenCloud Command Line Tools
  command: curl -O https://aberdeen.s3.amazonaws.com/toolkit/latest/aberdeen && chmod +x aberdeen
  when: aberdeen_cli is defined and aberdeen_cli

- name: Make AberdeenCloud Command Line Tools available system-wide
  command: install aberdeen /usr/bin
  sudo: true
  when: aberdeen_cli is defined and aberdeen_cli
