---

# http://www.aberdeencloud.com/docs/guides/command-line-tools

- name: Install AberdeenCloud Command Line Tools
  command: curl -O https://aberdeen.s3.amazonaws.com/toolkit/latest/aberdeen
  when: aberdeen_cli is defined and aberdeen_cli
  tags: aberdeen

- name: Install AberdeenCloud Command Line Tools
  file: path=aberdeen mode=764
  when: aberdeen_cli is defined and aberdeen_cli
  tags: aberdeen

- name: Make AberdeenCloud Command Line Tools available system-wide
  command: install aberdeen /usr/bin
  sudo: true
  when: aberdeen_cli is defined and aberdeen_cli
  tags: aberdeen
