---

# Create local drush site alias file
- template: src=vm.alias.drushrc.php.j2 dest=/home/vagrant/.drush/{{ boxname }}.{{ local_alias_name }}.alias.drushrc.php
  notify: drush cc drush
  when: php_install is defined and php_install == "y"
  tags: drush_aliases

# Copy/rename any custom remote site aliases from ../../settings/drush_aliases/
# TODO: Add validation here - file extension, number of files, check for duplication of local alias name etc
- copy: src={{ item }} dest=/home/vagrant/.drush/{{ boxname }}.aliases.drushrc.php
  with_fileglob:
    - ../../settings/drush_aliases/*
  notify: drush cc drush
  when: php_install is defined and php_install == "y"
  tags: drush_aliases