---

- name: Download the drupalgeddon drush extension
  command: drush dl drupalgeddon --yes chdir=/home/{{ user }}/.drush creates=/home/{{ user }}/.drush/drupalgeddon
  when: php_install
  notify: drush cc drush
