---
# Create directories outside of docroot/

- name: Create drush-dumps directory (above docroot)
  file: path=/var/www/site/drush-dumps state=directory owner=vagrant group=www-data mode=770
  sudo: true

- name: Create vlad_aux/private files directory if it doesn't exist
  file: path=/var/www/site/vlad_aux/private state=directory