---
- name: Custom | Create .drush_bashrc file
  command: cp /home/{{ user }}/drush-master/examples/example.bashrc /home/{{ user }}/.drush_bashrc creates=/home/{{ user }}/.drush_bashrc
  tags: custom
  when: php_install is defined and php_install == "y"

# @TODO work out how to *sensibly* add multiple lines so that we can do:
#
# if [ -f ~/.drush_bashrc ] ; then
#   . ~/.drush_bashrc
# fi
- name: Custom | Source .drush_bashrc from .bash_profile
  lineinfile:
    dest=/home/{{ user }}/.bashrc
    state=present
    line='. ~/.drush_bashrc'
  tags: custom
  when: php_install is defined and php_install == "y"